---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config              # ← Change if you rename this ConfigMap
  namespace: monitoring               # ← Match your chosen namespace
data:
  telegraf.conf: |
    [[inputs.kubernetes]]
      # bearer_token path is standard; leave unless you mount elsewhere
      bearer_token = "/var/run/secrets/kubernetes.io/serviceaccount/token"
    [[inputs.kube_inventory]]
    [[outputs.influxdb_v2]]
      # Change this URL if your InfluxDB service name, namespace or port differ
      urls = ["http://influxdb.monitoring.svc.cluster.local:8086"]
      # These env vars come from the influxdb-info secret—ensure the secret name matches
      token = "${INFLUX_TOKEN}"      # ← Injected from Secret; client must create this secret
      organization = "${INFLUX_ORG}" # ← Injected; client sets their Org name
      bucket = "${INFLUX_BUCKET}"    # ← Injected; client sets their Bucket name
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegraf                     # ← Change if you want a different SA name
  namespace: monitoring               # ← Match your namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telegraf-monitoring          # ← Change if naming convention differs
subjects:
  - kind: ServiceAccount
    name: telegraf                   # ← Must match the SA above
    namespace: monitoring            # ← Must match the SA’s namespace
roleRef:
  kind: ClusterRole
  name: cluster-admin                # ← Highly permissive; may want to scope to system:monitoring
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: telegraf                     # ← Change if you rename the DaemonSet
  namespace: monitoring               # ← Match your namespace
  labels:
    app: telegraf                    # ← Must match selector/template below
spec:
  selector:
    matchLabels:
      app: telegraf                  # ← Must match the pod template label
  template:
    metadata:
      labels:
        app: telegraf                # ← Must match selector above
    spec:
      serviceAccountName: telegraf   # ← SA you created above
      containers:
        - name: telegraf
          # Pin to a tested version, or upgrade as needed:
          image: influxdata/telegraf:1.34  # ←  Can bump this to e.g. 1.35, 1.36, etc.
          env:
            - name: INFLUX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-info   # ← Must match the Secret name holding your write token
                  key: token
            - name: INFLUX_ORG
              valueFrom:
                secretKeyRef:
                  name: influxdb-info   # ← Must match Secret name
                  key: org
            - name: INFLUX_BUCKET
              valueFrom:
                secretKeyRef:
                  name: influxdb-info   # ← Must match Secret name
                  key: bucket
          volumeMounts:
            - name: config
              # Where Telegraf expects its config:
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
      volumes:
        - name: config
          configMap:
            name: telegraf-config   # ← Must match the ConfigMap name above
